version: '3'

services:
  api:
    build:
      context: ./FastFinance_BackEnd
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    container_name: fastfinance_api
    restart: always
    env_file:
      - ./FastFinance_BackEnd/.env
    networks:
      - fastFinance
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      
  frontend: 
    build:
      context: ./fast_finance_front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: fastfinance_front
    restart: always
    networks:
      - fastFinance
    depends_on:
      - api
      
  db:
    image: postgres:16
    restart: always
    container_name: fastfinance_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastFinance
    ports:
      - '5435:5432'
    networks:
      - fastFinance
    volumes:
      - ./docker/db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastFinance"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  rabbitmq:                    
    image: rabbitmq:3-management
    container_name: fastfinance_rabbitmq
    ports:
      - '5672:5672'   
      - '15672:15672' 
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - fastFinance

networks:
  fastFinance: